import { useState, useEffect, useRef } from 'react'

/**
 * In-memory cache shared across all hook instances.
 * Persists across re-renders but cleared on page refresh.
 */
export const wikiCache = {}

/**
 * Fetches a thumbnail URL from Wikipedia REST API for a given page title.
 * Endpoint: https://en.wikipedia.org/api/rest_v1/page/summary/{title}
 * Returns the `thumbnail.source` field — a hotlink-friendly image URL.
 *
 * @param {string} wikiTitle — Wikipedia article title, e.g. "Arsenal_F.C."
 * @returns {{ url: string|null, loading: boolean, error: boolean }}
 */
export function useWikiImage(wikiTitle) {
    const [url, setUrl] = useState(wikiCache[wikiTitle]?.url ?? null)
    const [loading, setLoading] = useState(!wikiCache[wikiTitle])
    const [error, setError] = useState(wikiCache[wikiTitle]?.error ?? false)
    const abortRef = useRef(null)

    useEffect(() => {
        if (!wikiTitle) {
            setLoading(false)
            setError(true)
            return
        }

        // Already cached
        if (wikiCache[wikiTitle]) {
            setUrl(wikiCache[wikiTitle].url)
            setError(wikiCache[wikiTitle].error)
            setLoading(false)
            return
        }

        const controller = new AbortController()
        abortRef.current = controller

        setLoading(true)
        setError(false)

        const encoded = encodeURIComponent(wikiTitle)
        fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encoded}`, {
            signal: controller.signal,
        })
            .then((res) => {
                if (!res.ok) throw new Error(`HTTP ${res.status}`)
                return res.json()
            })
            .then((data) => {
                const imgUrl = data.thumbnail?.source || data.originalimage?.source || null
                wikiCache[wikiTitle] = { url: imgUrl, error: !imgUrl }
                setUrl(imgUrl)
                setError(!imgUrl)
                setLoading(false)
            })
            .catch((err) => {
                if (err.name !== 'AbortError') {
                    console.log(`[WikiAPI] Failed for "${wikiTitle}":`, err.message)
                    wikiCache[wikiTitle] = { url: null, error: true }
                    setError(true)
                    setLoading(false)
                }
            })

        return () => controller.abort()
    }, [wikiTitle])

    return { url, loading, error }
}

/**
 * Batch-fetch Wikipedia thumbnails for multiple titles.
 * Returns a map of { title: thumbnailUrl }.
 */
export async function fetchWikiImages(titles) {
    const results = {}
    const toFetch = titles.filter((t) => {
        if (wikiCache[t]) {
            results[t] = wikiCache[t].url
            return false
        }
        return true
    })

    const promises = toFetch.map(async (title) => {
        try {
            const encoded = encodeURIComponent(title)
            const res = await fetch(
                `https://en.wikipedia.org/api/rest_v1/page/summary/${encoded}`
            )
            if (!res.ok) throw new Error(`HTTP ${res.status}`)
            const data = await res.json()
            const imgUrl = data.thumbnail?.source || data.originalimage?.source || null
            wikiCache[title] = { url: imgUrl, error: !imgUrl }
            results[title] = imgUrl
        } catch (err) {
            console.log(`[WikiAPI] Failed for "${title}":`, err.message)
            wikiCache[title] = { url: null, error: true }
            results[title] = null
        }
    })

    await Promise.all(promises)
    return results
}

/* ── Club name → Wikipedia article title mapping ── */
export const clubWikiTitles = {
    'PSG': 'Paris_Saint-Germain_F.C.',
    'Arsenal': 'Arsenal_F.C.',
    'Real Madrid': 'Real_Madrid_CF',
    'Liverpool': 'Liverpool_F.C.',
    'Man City': 'Manchester_City_F.C.',
    'Fenerbahçe': 'Fenerbahçe_S.K._(football)',
    'Bolton': 'Bolton_Wanderers_F.C.',
    'Chelsea': 'Chelsea_F.C.',
    'Juventus': 'Juventus_F.C.',
    'Mallorca': 'RCD_Mallorca',
    'Barcelona': 'FC_Barcelona',
    'Inter Milan': 'Inter_Milan',
    'Anzhi': 'FC_Anzhi_Makhachkala',
    'Everton': 'Everton_F.C.',
    'Sampdoria': 'U.C._Sampdoria',
    'Antalyaspor': 'Antalyaspor',
    'Konyaspor': 'Konyaspor',
    'Ajax': 'AFC_Ajax',
    'Galatasaray': 'Galatasaray_S.K._(football)',
    'Nice': 'OGC_Nice',
    'Al-Gharafa': 'Al-Gharafa_SC',
    'Sporting CP': 'Sporting_CP',
    'Porto': 'FC_Porto',
    'Beşiktaş': 'Beşiktaş_J.K.',
    'Al-Ahli': 'Al_Ahli_Club_(Dubai)',
    'Kasımpaşa': 'Kasımpaşa_S.K.',
    'Vitória': 'Vitória_S.C.',
    'Malmö': 'Malmö_FF',
    'AC Milan': 'AC_Milan',
    'Man Utd': 'Manchester_United_F.C.',
    'LA Galaxy': 'LA_Galaxy',
    'Shanghai Shenhua': 'Shanghai_Shenhua_F.C.',
    'West Brom': 'West_Bromwich_Albion_F.C.',
    'Botafogo': 'Botafogo_de_Futebol_e_Regatas',
    'Vasco da Gama': 'CR_Vasco_da_Gama',
    'Grêmio': 'Grêmio_Foot-Ball_Porto_Alegrense',
    'Alavés': 'Deportivo_Alavés',
    'Sakaryaspor': 'Sakaryaspor',
    'Middlesbrough': 'Middlesbrough_F.C.',
    'Stoke City': 'Stoke_City_F.C.',
    'Wolfsburg': 'VfL_Wolfsburg',
    'Bursaspor': 'Bursaspor',
    'Atlético Madrid': 'Atlético_Madrid',
    'Sagan Tosu': 'Sagan_Tosu',
    'Santos': 'Santos_FC',
    'Guangzhou': 'Guangzhou_F.C.',
    'Atlético Mineiro': 'Clube_Atlético_Mineiro',
    'Sivasspor': 'Sivasspor',
    'İstanbul Başakşehir': 'İstanbul_Başakşehir_F.K.',
    'Metz': 'FC_Metz',
    'Monaco': 'AS_Monaco_FC',
    'Tottenham': 'Tottenham_Hotspur_F.C.',
    'Crystal Palace': 'Crystal_Palace_F.C.',
    'Kayserispor': 'Kayserispor',
    'Barnet': 'Barnet_F.C.',
    'CSKA Sofia': 'PFC_CSKA_Sofia',
    'Bayer Leverkusen': 'Bayer_04_Leverkusen',
    'Fulham': 'Fulham_F.C.',
    'PAOK': 'PAOK_FC',
    'Kerala Blasters': 'Kerala_Blasters_FC',
    'River Plate': 'Club_Atlético_River_Plate',
    'Parma': 'Parma_Calcio_1913',
    'Lazio': 'S.S._Lazio',
    'Genoa': 'Genoa_CFC',
    'Newcastle': 'Newcastle_United_F.C.',
    'Platense': 'Club_Atlético_Platense',
    'Hércules': 'Hércules_CF',
    "Newell's Old Boys": "Newell%27s_Old_Boys",
    'Wolves': 'Wolverhampton_Wanderers_F.C.',
    'Coventry': 'Coventry_City_F.C.',
    'Leeds': 'Leeds_United_F.C.',
    'Celtic': 'Celtic_F.C.',
    'Aston Villa': 'Aston_Villa_F.C.',
    'New York Red Bulls': 'New_York_Red_Bulls',
    'Köln': '1._FC_Köln',
    'Bayern Munich': 'FC_Bayern_Munich',
    'Vissel Kobe': 'Vissel_Kobe',
    'Górnik Zabrze': 'Górnik_Zabrze',
    'Brescia': 'Brescia_Calcio',
    'Adana Demirspor': 'Adana_Demirspor',
    'Sion': 'FC_Sion',
    'Eyüpspor': 'Eyüpspor',
    'Feyenoord': 'Feyenoord',
    'Boca Juniors': 'Boca_Juniors',
    'West Ham': 'West_Ham_United_F.C.',
    'Marítimo': 'C.S._Marítimo',
    'Stuttgart': 'VfB_Stuttgart',
    'Fiorentina': 'ACF_Fiorentina',
    'Preston': 'Preston_North_End_F.C.',
    'Cannes': 'AS_Cannes',
    'Valencia': 'Valencia_CF',
    'Orlando City': 'Orlando_City_SC',
    'Venezia': 'Venezia_FC',
    'Torino': 'Torino_F.C.',
    'Blackburn': 'Blackburn_Rovers_F.C.',
    'Danubio': 'Danubio_F.C.',
    'Palermo': 'Palermo_FC',
    'Napoli': 'S.S.C._Napoli',
    'Beveren': 'K.S.K._Beveren',
    'Metalurh Donetsk': 'FC_Metalurh_Donetsk',
    'Olympiacos': 'Olympiacos_F.C.',
    'Roma': 'A.S._Roma',
    'Derby County': 'Derby_County_F.C.',
    'Helsingborg': 'Helsingborgs_IF',
    'Le Havre': 'Le_Havre_AC',
    'Portsmouth': 'Portsmouth_F.C.',
    'Lokomotiv Moscow': 'FC_Lokomotiv_Moscow',
    'Marseille': 'Olympique_de_Marseille',
    'Flamengo': 'CR_Flamengo',
    'São Paulo': 'São_Paulo_FC',
    'Atlético PR': 'Club_Athletico_Paranaense',
    'Corinthians': 'Sport_Club_Corinthians_Paulista',
    'Schalke 04': 'FC_Schalke_04',
    'Al-Sadd': 'Al-Sadd_SC',
    'New York Cosmos': 'New_York_Cosmos_(2010)',
    'Auxerre': 'AJ_Auxerre',
    'Sunderland': 'Sunderland_A.F.C.',
    'Panathinaikos': 'Panathinaikos_F.C.',
    'QPR': 'Queens_Park_Rangers_F.C.',
    'Bastia': 'SC_Bastia',
    'Southampton': 'Southampton_F.C.',
    'Burnley': 'Burnley_F.C.',
    'Birmingham': 'Birmingham_City_F.C.',
    'Levante': 'Levante_UD',
    'Seattle Sounders': 'Seattle_Sounders_FC',
    'Sevilla': 'Sevilla_FC',
    'Benfica': 'S.L._Benfica',
    'Málaga': 'Málaga_CF',
    'Verona': 'Hellas_Verona_FC',
    'Banfield': 'Club_Atlético_Banfield',
    'Bologna': 'Bologna_FC_1909',
    'AEK Athens': 'AEK_Athens_F.C.',
    'Groningen': 'FC_Groningen',
    'PSV': 'PSV_Eindhoven',
    'Deportivo': 'Deportivo_de_La_Coruña',
    'Cruzeiro': 'Cruzeiro_Esporte_Clube',
    'Bunyodkor': 'FC_Bunyodkor',
    'Mogi Mirim': 'Mogi_Mirim_Esporte_Clube',
    'Palmeiras': 'Sociedade_Esportiva_Palmeiras',
    'Eskişehirspor': 'Eskişehirspor',
    'Şekerspor': 'Etimesgut_Şekerspor',
    'Trabzonspor': 'Trabzonspor',
    'Elazığspor': 'Elazığspor',
    'St. Gallen': 'FC_St._Gallen',
    'Şanlıurfaspor': 'Şanlıurfaspor',
    'Bahia': 'Esporte_Clube_Bahia',
    'Pumas UNAM': 'Club_Universidad_Nacional',
    'Le Mans': 'Le_Mans_FC',
    'Guingamp': 'En_Avant_de_Guingamp',
    'Montreal Impact': 'CF_Montréal',
    'Mumbai City': 'Mumbai_City_FC',
    'Rubin Kazan': 'FC_Rubin_Kazan',
    'Pune City': 'FC_Pune_City',
    'ATK': 'ATK_Mohun_Bagan_FC',
    // New clubs for IDs 45-100
    'Cardiff': 'Cardiff_City_F.C.',
    'Perth Glory': 'Perth_Glory_FC',
    'Muangthong United': 'Muangthong_United_F.C.',
    'Pisa': 'A.C._Pisa_1909',
    'Ravenna': 'Ravenna_F.C.',
    'Atalanta': 'Atalanta_BC',
    'Sheffield United': 'Sheffield_United_F.C.',
    'Ipswich': 'Ipswich_Town_F.C.',
    'Charlton': 'Charlton_Athletic_F.C.',
    'Wigan': 'Wigan_Athletic_F.C.',
    'Leicester': 'Leicester_City_F.C.',
    'Bristol City': 'Bristol_City_F.C.',
    'Man United': 'Manchester_United_F.C.',
    'Nott. Forest': 'Nottingham_Forest_F.C.',
    'Nagoya Grampus': 'Nagoya_Grampus',
    'VVV-Venlo': 'VVV-Venlo',
    'CSKA Moscow': 'PFC_CSKA_Moscow',
    'Pachuca': 'C.F._Pachuca',
    'Melbourne Victory': 'Melbourne_Victory_FC',
    'Vitesse': 'SBV_Vitesse',
    'Portimonense': 'Portimonense_S.C.',
    'İstanbulspor': 'İstanbulspor',
    'Fortuna Düsseldorf': 'Fortuna_Düsseldorf',
    'Olimpia': 'Club_Olimpia',
    'Real Betis': 'Real_Betis',
    'Cruz Azul': 'Cruz_Azul',
    'Delhi Dynamos': 'Delhi_Dynamos_FC',
    'Ajax Cape Town': 'Ajax_Cape_Town_F.C.',
    'Celta Vigo': 'RC_Celta_de_Vigo',
    'Orlando Pirates': 'Orlando_Pirates',
    'Dijon': 'Dijon_FCO',
    'Saint-Étienne': 'AS_Saint-Étienne',
    'Borussia Dortmund': 'Borussia_Dortmund',
    'Sochaux': 'FC_Sochaux-Montbéliard',
    'Rennes': 'Stade_Rennais_F.C.',
    'Lens': 'RC_Lens',
    'Doncaster': 'Doncaster_Rovers_F.C.',
    'Rangers': 'Rangers_F.C.',
    'Norwich': 'Norwich_City_F.C.',
    'Halmstad': 'Halmstads_BK',
    'Shimizu S-Pulse': 'Shimizu_S-Pulse',
    'Millwall': 'Millwall_F.C.',
    'Melbourne City': 'Melbourne_City_FC',
    'Jamshedpur': 'Jamshedpur_FC',
    'Espanyol': 'RCD_Espanyol',
    'Córdoba': 'Córdoba_CF',
    'Extremadura': 'Extremadura_UD',
    'Catania': 'Calcio_Catania',
    'Hertha BSC': 'Hertha_BSC',
    'Las Palmas': 'UD_Las_Palmas',
    'Eintracht Frankfurt': 'Eintracht_Frankfurt',
    'Sassuolo': 'U.S._Sassuolo_Calcio',
    'Monza': 'A.C._Monza',
    'Rayo Vallecano': 'Rayo_Vallecano',
    'Inter Miami': 'Inter_Miami_CF',
    'Cobreloa': 'Club_de_Deportes_Cobreloa',
    'Tampa Bay Rowdies': 'Tampa_Bay_Rowdies',
    'Lille': 'Lille_OSC',
    'Hebei FC': 'Hebei_F.C.',
    'Club Brugge': 'Club_Brugge_KV',
    'Villarreal': 'Villarreal_CF',
    'Granada': 'Granada_CF',
    'Hull City': 'Hull_City_A.F.C.',
    'Lyon': 'Olympique_Lyonnais',
    'Valladolid': 'Real_Valladolid',
    'Bordeaux': 'Girondins_de_Bordeaux',
    'Al-Ahli Dubai': 'Al-Ahli_Club_(Dubai)',
    'Hoffenheim': 'TSG_1899_Hoffenheim',
    'Göztepe': 'Göztepe_S.K.',
    'BATE Borisov': 'FC_BATE_Borisov',
    'Gençlerbirliği': 'Gençlerbirliği_S.K.',
    'Kaiserslautern': '1._FC_Kaiserslautern',
    'Werder Bremen': 'SV_Werder_Bremen',
    'Twente': 'FC_Twente',
    'Anderlecht': 'R.S.C._Anderlecht',
    'Westerlo': 'K.V.C._Westerlo',
    'Al Ain': 'Al_Ain_FC',
    'Shanghai SIPG': 'Shanghai_Port_F.C.',
    'NorthEast United': 'NorthEast_United_FC',
    'Legon Cities': 'Legon_Cities_FC',
    'Stoke': 'Stoke_City_F.C.',
    'Spartak Moscow': 'FC_Spartak_Moscow',
    'Gil Vicente': 'Gil_Vicente_F.C.',
    'Maccabi Haifa': 'Maccabi_Haifa_F.C.',
    'Reading': 'Reading_F.C.',
    'Derby': 'Derby_County_F.C.',
    'Brighton': 'Brighton_%26_Hove_Albion_F.C.',
    'Copenhagen': 'F.C._Copenhagen',
    'Rosenborg': 'Rosenborg_BK',
    'Karabükspor': 'Kardemir_Karabükspor',
    'Almería': 'UD_Almería',
    'Al-Nasr': 'Al-Nasr_SC_(Dubai)',
    'Cádiz': 'Cádiz_CF',
    'Hajduk Split': 'HNK_Hajduk_Split',
    'Zulte Waregem': 'S.V._Zulte_Waregem',
    'Rapid Vienna': 'SK_Rapid_Wien',
    'Beijing Renhe': 'Beijing_Renhe_F.C.',
    'Getafe': 'Getafe_CF',
    'Çaykur Rizespor': 'Çaykur_Rizespor',
    'Bari': 'S.S.C._Bari',
    'Real Oviedo': 'Real_Oviedo',
    'Hannover': 'Hannover_96',
    'Braga': 'S.C._Braga',
    'Shandong Luneng': 'Shandong_Taishan_F.C.',
    'Alanyaspor': 'Alanyaspor',
    'Sport Recife': 'Sport_Club_do_Recife',
    'Grasshoppers': 'Grasshopper_Club_Zürich',
    'Kuban Krasnodar': 'FC_Kuban_Krasnodar',
    'Ural': 'FC_Ural_Yekaterinburg',
    'Ulsan': 'Ulsan_Hyundai_FC',
    'Al-Ahli Saudi': 'Al-Ahli_Saudi_FC',
    'Lierse': 'Lierse_S.K.',
    'Roda JC': 'Roda_JC_Kerkrade',
    'Colchester': 'Colchester_United_F.C.',
    'Apollon Limassol': 'Apollon_Limassol_FC',
    'Lugano': 'FC_Lugano',
    'Beijing Guoan': 'Beijing_Guoan_F.C.',
    'Atlético Junior': 'Atlético_Junior',
    'Mpumalanga Black Aces': 'Mpumalanga_Black_Aces_F.C.',
    'Cape Town': 'Cape_Town_City_F.C.',
    'Delta Force': 'Delta_Force_FC',
    'Semassi': 'Semassi_SC',
    'Kobuscorp': 'Kabuscorp_Sport_Clube_do_Palanca',
    'North Queensland Fury': 'North_Queensland_Fury',
    'Millonarios': 'Millonarios_FC',
    'Cobreloa': 'Club_de_Deportes_Cobreloa',
    'Shabab Al Ahli': 'Shabab_Al-Ahli_Dubai_FC',
    'Liberty Professionals': 'Liberty_Professionals_FC',
    'Atlético PR': 'Club_Athletico_Paranaense',
    'New York Cosmos': 'New_York_Cosmos_(2010)',
    'Qingdao Huanghai': 'Qingdao_FC',
    'Metalurh Donetsk': 'FC_Metalurh_Donetsk',
    'Beveren': 'K.S.K._Beveren',
    'ASEC Mimosas': 'ASEC_Mimosas',
    'Danubio': 'Danubio_F.C.',
    'Helsingborg': 'Helsingborgs_IF',
    'Halmstad': 'Halmstads_BK',
    'Shimizu S-Pulse': 'Shimizu_S-Pulse',
    'Nagoya Grampus': 'Nagoya_Grampus',
    'Neftçi': 'Neftchi_Baku_PFK',
    'Sūduva': 'FK_Sūduva',
    'Beijing Guoan': 'Beijing_Guoan_F.C.',
    'Altay': 'Altay_SK',
    'Göztepe': 'Göztepe_S.K.',
    'Udinese': 'Udinese_Calcio',
    'Brentford': 'Brentford_F.C.',
    'Crotone': 'F.C._Crotone',
    'Beira-Mar': 'S.C._Beira-Mar',
    'Newcastle Jets': 'Newcastle_Jets_FC',
    'Qatar SC': 'Qatar_SC',
    '1461 Trabzon': '1461_Trabzon_FK',
    'Van Spor': 'Van_Spor_FK',
    'Anorthosis': 'Anorthosis_Famagusta_F.C.',
    'São Caetano': 'Associação_Desportiva_São_Caetano',
    'Criciúma': 'Criciúma_E.C.',
    'Manisaspor': 'Manisaspor',
    'Phoenix Rising': 'Phoenix_Rising_FC',
    'Reggina': 'Reggina_1914',
    'Bandırmaspor': 'Bandırmaspor_FK',
    // New clubs for IDs 101-150
    'Fluminense': 'Fluminense_FC',
    'Grêmio': 'Grêmio_Foot-Ball_Porto_Alegrense',
    'PSV Eindhoven': 'PSV_Eindhoven',
    'Utrecht': 'FC_Utrecht',
    'Dinamo Zagreb': 'GNK_Dinamo_Zagreb',
    'Lech Poznań': 'Lech_Poznań',
    'Željezničar': 'FK_Željezničar',
    'Standard Liège': 'Standard_Liège',
    'Vojvodina': 'FK_Vojvodina',
    'Vålerenga': 'Vålerenga_Fotball',
    'Rosenborg': 'Rosenborg_BK',
    'Olympiacos': 'Olympiacos_F.C.',
    'Colo-Colo': 'Colo-Colo',
    'Nacional': 'Club_Nacional_de_Football',
    'Alianza Lima': 'Club_Alianza_Lima',
    'RB Salzburg': 'FC_Red_Bull_Salzburg',
    'Real Sociedad': 'Real_Sociedad',
    'Swansea City': 'Swansea_City_AFC',
    'Nottingham Forest': 'Nottingham_Forest_F.C.',
    'Tottenham Hotspur': 'Tottenham_Hotspur_F.C.',
    'Leicester City': 'Leicester_City_F.C.',
    'Aston Villa': 'Aston_Villa_F.C.',
    'Stoke City': 'Stoke_City_F.C.',
    'Millwall': 'Millwall_F.C.',
    'Leyton Orient': 'Leyton_Orient_F.C.',
    'Norwich': 'Norwich_City_F.C.',
    'Montpellier': 'Montpellier_HSC',
    'Troyes': 'ESTAC_Troyes',
    'Strasbourg': 'RC_Strasbourg_Alsace',
    'Grenoble': 'Grenoble_Foot_38',
    'Metz': 'Football_Club_de_Metz',
    'Lille': 'LOSC_Lille',
    'Lyon': 'Olympique_Lyonnais',
    'Albacete': 'Albacete_Balompié',
    'Levante': 'Levante_UD',
    'Getafe': 'Getafe_CF',
    'Mallorca': 'RCD_Mallorca',
    'Recreativo': 'Recreativo_de_Huelva',
    'Basel': 'FC_Basel',
    'Midtjylland': 'FC_Midtjylland',
    'Como': 'Calcio_Como',
    'Perugia': 'A.C._Perugia_Calcio',
    'Salernitana': 'Unione_Sportiva_Salernitana',
    'Rangers': 'Rangers_F.C.',
    'Hamburg': 'Hamburger_SV',
    'Zenit': 'FC_Zenit_Saint_Petersburg',
    'CSKA Moscow': 'PFC_CSKA_Moscow',
    'Lokomotiv Moscow': 'FC_Lokomotiv_Moscow',
    'Al-Hilal': 'Al-Hilal_FC',
    'Al-Nassr': 'Al-Nassr_FC',
    'Al-Ittihad': 'Al-Ittihad_Club',
    'Al-Sadd': 'Al-Sadd_SC',
    'Al Mokawloon': 'Al-Mokawloon_Al-Arab_SC',
    'Al-Jazira': 'Al_Jazira_Club',
    'Kawasaki Frontale': 'Kawasaki_Frontale',
    'Consadole Sapporo': 'Hokkaido_Consadole_Sapporo',
    'Tokyo Verdy': 'Tokyo_Verdy',
    'Shanghai SIPG': 'Shanghai_Port_F.C.',
    'Hebei': 'Hebei_F.C.',
    'Flamengo': 'Clube_de_Regatas_do_Flamengo',
    'Atlético Mineiro': 'Clube_Atlético_Mineiro',
    'Cruzeiro': 'Cruzeiro_Esporte_Clube',
    'Inter Miami': 'Inter_Miami_CF',
    'São Paulo': 'São_Paulo_FC',
    'Independiente': 'Club_Atlético_Independiente',
    'River Plate': 'Club_Atlético_River_Plate',
    'Estudiantes': 'Estudiantes_de_La_Plata',
    'Rosario Central': 'Rosario_Central',
    "Newell's Old Boys": "Newell's_Old_Boys",
    'Guadalajara': 'Deportivo_Guadalajara',
    'Monterrey': 'C.F._Monterrey',
    'Pumas UNAM': 'Club_Universidad_Nacional',
    'LAFC': 'Los_Angeles_FC',
    'LA Galaxy': 'LA_Galaxy',
    'Vancouver Whitecaps': 'Vancouver_Whitecaps_FC',
    'Minnesota United': 'Minnesota_United_FC',
    'Orlando City': 'Orlando_City_SC',
    'Athletico Paranaense': 'Club_Athletico_Paranaense',
    'Avaí': 'Avaí_FC',
    'Vitória': 'Esporte_Clube_Vitória',
    'Corinthians': 'Sport_Club_Corinthians_Paulista',
    'Cerro Porteño': 'Club_Cerro_Porteño',
    'Club León': 'Club_León',
    'Envigado': 'Envigado_FC',
    'Boavista': 'Boavista_FC',
    'Saprissa': 'Deportivo_Saprissa',
    'Yeni Malatyaspor': 'Yeni_Malatyaspor',
    'Konyaspor': 'Konyaspor',
    'Ankaragücü': 'MKE_Ankaragücü',
    'Lazio': 'S.S._Lazio',
    'Napoli': 'S.S.C._Napoli',
    "Borussia M'gladbach": 'Borussia_Mönchengladbach',
    'Teplice': 'FK_Teplice',
    'Lechia Gdańsk': 'Lechia_Gdańsk',
    'Rot Weiss Ahlen': 'Rot_Weiss_Ahlen',
    'Esbjerg': 'Esbjerg_fB',
    'Johor DT': 'Johor_Darul_Takzim_F.C.',
    'Desportivo Aves': 'C.D._Aves',
    'Alverca': 'F.C._Alverca',
    'Salgueiros': 'S.C._Salgueiros',
    'Penafiel': 'G.D._Chaves',
    'Arles-Avignon': 'AC_Arles-Avignon',
    'Istres': 'Istres_FC',
    'Tours': 'Tours_FC',
    'Rubin Kazan': 'FC_Rubin_Kazan',
    'Al-Rayyan': 'Al-Rayyan_SC',
    'Botafogo-SP': 'Botafogo_FC_(Ribeirão_Preto)',
    'Quick Boys': 'Quick_Boys',
    'Adana Demirspor': 'Adana_Demirspor',
}

/* ── Player name → Wikipedia article title mapping ── */
export const playerWikiTitles = {
    'Nicolas Anelka': 'Nicolas_Anelka',
    "Samuel Eto'o": "Samuel_Eto'o",
    'Wesley Sneijder': 'Wesley_Sneijder',
    'Ricardo Quaresma': 'Ricardo_Quaresma',
    'Zlatan Ibrahimovic': 'Zlatan_Ibrahimović',
    'Rivaldo': 'Rivaldo',
    'Clarence Seedorf': 'Clarence_Seedorf',
    'Mario Jardel': 'Mário_Jardel',
    'Tuncay Şanlı': 'Tuncay_Şanlı',
    'Didier Drogba': 'Didier_Drogba',
    'Dani Alves': 'Dani_Alves',
    'Batuhan Karadeniz': 'Batuhan_Karadeniz',
    'Fernando Torres': 'Fernando_Torres',
    'Robinho': 'Robinho',
    'Emmanuel Adebayor': 'Emmanuel_Adebayor',
    'Edgar Davids': 'Edgar_Davids',
    'Dimitar Berbatov': 'Dimitar_Berbatov',
    'Hernán Crespo': 'Hernán_Crespo',
    'Michael Owen': 'Michael_Owen',
    'David Trezeguet': 'David_Trezeguet',
    'Robbie Keane': 'Robbie_Keane',
    'Thierry Henry': 'Thierry_Henry',
    'Lukas Podolski': 'Lukas_Podolski',
    'Mario Balotelli': 'Mario_Balotelli',
    'Arda Turan': 'Arda_Turan',
    'Robin van Persie': 'Robin_van_Persie',
    'Carlos Tevez': 'Carlos_Tevez',
    'Pepe': 'Pepe_(footballer,_born_1983)',
    'Guti': 'Guti_(footballer)',
    'Mario Gomez': 'Mario_Gómez',
    'David Beckham': 'David_Beckham',
    'Patrick Vieira': 'Patrick_Vieira',
    'Nani': 'Nani_(footballer)',
    'Hakan Şükür': 'Hakan_Şükür',
    'Edinson Cavani': 'Edinson_Cavani',
    'Yaya Touré': 'Yaya_Touré',
    'Ashley Cole': 'Ashley_Cole',
    'Henrik Larsson': 'Henrik_Larsson',
    'Lassana Diarra': 'Lassana_Diarra',
    'Adriano': 'Adriano_Leite_Ribeiro',
    'Raúl': 'Raúl_(footballer)',
    'Djibril Cissé': 'Djibril_Cissé',
    'Peter Crouch': 'Peter_Crouch',
    'Obafemi Martins': 'Obafemi_Martins',
    'Javier Saviola': 'Javier_Saviola',
    'Julio Cruz': 'Julio_Cruz',
    'Emre Belözoğlu': 'Emre_Belözoğlu',
    'Arjen Robben': 'Arjen_Robben',
    'Kaká': 'Kaká',
    // New players for IDs 45-100
    'Robbie Fowler': 'Robbie_Fowler',
    'Christian Vieri': 'Christian_Vieri',
    'Marcus Bent': 'Marcus_Bent',
    'Andy Cole': 'Andrew_Cole',
    'Keisuke Honda': 'Keisuke_Honda',
    'Sergen Yalçın': 'Sergen_Yalçın',
    'Burak Yılmaz': 'Burak_Yılmaz',
    'Roque Santa Cruz': 'Roque_Santa_Cruz',
    'Florent Malouda': 'Florent_Malouda',
    'Benni McCarthy': 'Benni_McCarthy',
    'Pierre-Emerick Aubameyang': 'Pierre-Emerick_Aubameyang',
    'El Hadji Diouf': 'El_Hadji_Diouf',
    'Craig Bellamy': 'Craig_Bellamy',
    'Freddie Ljungberg': 'Freddie_Ljungberg',
    'Salomon Kalou': 'Salomon_Kalou',
    'Tim Cahill': 'Tim_Cahill_(footballer)',
    'José Antonio Reyes': 'José_Antonio_Reyes',
    'Júlio Baptista': 'Júlio_Baptista',
    'Maxi López': 'Maxi_López',
    'Kevin-Prince Boateng': 'Kevin-Prince_Boateng',
    'Radamel Falcao': 'Radamel_Falcao',
    'Gonzalo Higuaín': 'Gonzalo_Higuaín',
    'Alexis Sánchez': 'Alexis_Sánchez',
    'Daniel Sturridge': 'Daniel_Sturridge',
    'Joe Cole': 'Joe_Cole',
    'Gervinho': 'Gervinho',
    'Carlos Bacca': 'Carlos_Bacca',
    'Hatem Ben Arfa': 'Hatem_Ben_Arfa',
    'Moussa Sow': 'Moussa_Sow',
    'Demba Ba': 'Demba_Ba',
    'Alexander Hleb': 'Aliaksandr_Hleb',
    'Miroslav Klose': 'Miroslav_Klose',
    'Álvaro Morata': 'Álvaro_Morata',
    'Nacer Chadli': 'Nacer_Chadli',
    'Asamoah Gyan': 'Asamoah_Gyan',
    'Victor Moses': 'Victor_Moses',
    'Yakubu Aiyegbeni': 'Yakubu_Aiyegbeni',
    'Darren Bent': 'Darren_Bent',
    'Nicklas Bendtner': 'Nicklas_Bendtner',
    'Emmanuel Emenike': 'Emmanuel_Emenike',
    'Álvaro Negredo': 'Álvaro_Negredo',
    'Nikica Jelavić': 'Nikica_Jelavić',
    'Loïc Rémy': 'Loïc_Rémy',
    'Abel Xavier': 'Abel_Xavier',
    'Tiago Mendes': 'Tiago_Cardoso_Mendes',
    'Vagner Love': 'Vagner_Love',
    'Benjani Mwaruwari': 'Benjani_Mwaruwari',
    'Roman Pavlyuchenko': 'Roman_Pavlyuchenko',
    'Grafite': 'Grafite_(footballer)',
    'Arouna Koné': 'Arouna_Koné',
    'Darren Ambrose': 'Darren_Ambrose',
    // New players for IDs 101-150
    'Pepe Reina': 'Pepe_Reina',
    'Michy Batshuayi': 'Michy_Batshuayi',
    'Esteban Cambiasso': 'Esteban_Cambiasso',
    'Miloš Krasić': 'Miloš_Krasić',
    'Gökhan Töre': 'Gökhan_Töre',
    'Jefferson Farfán': 'Jefferson_Farfán',
    'Cesc Fàbregas': 'Cesc_Fàbregas',
    'Simao Sabrosa': 'Simão_Sabrosa',
    'Gennaro Gattuso': 'Gennaro_Gattuso',
    'John Carew': 'John_Carew',
    'Deco': 'Deco_(footballer)',
    'Dirk Kuyt': 'Dirk_Kuyt',
    'Diego Costa': 'Diego_Costa',
    'Raul Meireles': 'Raul_Meireles',
    'Mamadou Niang': 'Mamadou_Niang',
    'Daniel Güiza': 'Daniel_Güiza',
    'Rafael van der Vaart': 'Rafael_van_der_Vaart',
    'Javier Mascherano': 'Javier_Mascherano',
    'Gabriel Heinze': 'Gabriel_Heinze',
    'Maicon': 'Maicon',
    'Hulk': 'Hulk_(footballer)',
    'Edin Džeko': 'Edin_Džeko',
    'James Rodríguez': 'James_Rodríguez',
    'Bafétimbi Gomis': 'Bafétimbi_Gomis',
    'Javier Hernández (Chicharito)': 'Javier_Hernández_(footballer)',
    'Sergio Ramos': 'Sergio_Ramos',
    'Keylor Navas': 'Keylor_Navas',
    'Arturo Vidal': 'Arturo_Vidal',
    'Ángel Di María': 'Ángel_Di_María',
    'Olivier Giroud': 'Olivier_Giroud',
    'Cristiano Ronaldo': 'Cristiano_Ronaldo',
    'Lionel Messi': 'Lionel_Messi',
    'Robert Lewandowski': 'Robert_Lewandowski',
    'Harry Kane': 'Harry_Kane',
    'Mohamed Salah': 'Mohamed_Salah',
    'Sadio Mané': 'Sadio_Mané',
    'Luka Modrić': 'Luka_Modrić',
    'Neymar': 'Neymar',
    'Karim Benzema': 'Karim_Benzema',
    'Luis Suárez': 'Luis_Suárez',
    'Thomas Müller': 'Thomas_Müller',
    'Thiago Silva': 'Thiago_Silva',
    'Marco Reus': 'Marco_Reus',
    'Toni Kroos': 'Toni_Kroos',
    'Mats Hummels': 'Mats_Hummels',
    'Manuel Neuer': 'Manuel_Neuer',
    'Antoine Griezmann': 'Antoine_Griezmann',
}
